### ISSUE TITLE
wrong diagram

### ISSUE THREAD

**Issue by Innoecho** [FantasyJXF/Translation#32]
@FantasyJXF please help to correct the third diagram in [offboard-control](https://github.com/FantasyJXF/Translation/blob/master/10_Robotics-using-ROS/offboard-control.md), I have tested it in the [live editor](http://knsv.github.io/mermaid/live_editor/), but it does not work in [our book](https://fantasyjxf.gitbooks.io/px4-wiki/content/10_Robotics-using-ROS/offboard-control.html)

**Comment by FantasyJXF** [comment]
I see. The diagram in the official website also failed to display,I'll figure it out later.
I's very nice of you to find the problem

**Comment by FantasyJXF** [comment]
The problem has been solved. It's bacause of the builder,there are too much “Space”.
Try the live editor below about "mermaid"
http://knsv.github.io/mermaid/live_editor/

**Comment by Innoecho** [comment]
thx
